### ISSUE TITLE
some warning

### ISSUE THREAD

**Issue by deadblackhole** [basehc/IPEV#16]
Hello 

I get the following warning when I run the software with my own files, and the result is empty, but the example file works fine

INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
/home/ws4/miniconda2/envs/IPEV/lib/python3.8/site-packages/sgt/sgt.py:95: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
for v in alphabets if v in sequence]
 I want to know what is the reason for this, is it my own file?Does this warning indicate a file failure?

**Comment by basehc** [comment]
The above warning is normal, but the empty result is not. Could you provide the fastas file?

**Comment by deadblackhole** [comment]
Thank you for your reply. 
I put the fasta file in the same folder as run.py and run it again to output the result. I thought I could customize the path when I passed the file, because the software default output file is the same as the input file.Maybe some improvements could be made?
Another problem is that the software runs on all of my cpus by default, and there seem to be no parameters that control cpu usage, so I can't run the software and do anything else at the same time.

**Comment by basehc** [comment]
Thank you for your suggestion, I will continue to improve the tools.
